### ISSUE TITLE
Can complexType be included from other file?

### ISSUE THREAD

**Issue by Light14** [MichielCM/xsd2html2xml#5] opened 2017-10-31 12:27 UTC
Hi,
thank you for your great work at first!
May we include complexType from another file, or even from current file?
For example type definition: `<xs:complexType name="includedType">...</xs:complexType>`
and
`<xs:element name="includedType" type="includedType"/>`, where I expect content from complexType defined above.
I can't get it to work. Can you please help me?
Thank you

**Comment by MichielCM** [comment] 2017-10-31 12:37
Hi! Yes, that should be possible.

I encountered a problem with that last week, though. It should be fixed in the current version of xsd+xml2html.xsl. (So no the latest release but the latest file upload).

**Comment by Light14** [comment] 2017-11-01 05:53
Yes, it works in latest version, thank you.
I found that `xs:complexType/xs:complexContent/xs:sequence` isn't processing, so I have added this code to handle-complex-element template:
`<xsl:apply-templates select="xs:complexType/xs:sequence
					|xs:complexType/xs:complexContent/xs:sequence`
...
`|exsl:node-set($namespace-documents)//xs:complexType[@name=$type-suffix]/xs:complexContent/xs:sequence`
I'm not experienced in transformations, so I don't know is this way correct or not.
I also noticed that `<xs:extension base="extb:SomeBase">` is not working, and still did not found why.

**Comment by MichielCM** [comment] 2017-11-01 09:33
I'll look into the complexType/complexContent problem, that seems odd.

The base="extb:SomeBase" should work, there are similar examples in the namespaces-sample folder. Are you sure that the namespace for extb is correctly declared? Is there an import tag referencing any file references for that namespace?

**Comment by MichielCM** [comment] 2017-11-01 09:53
Alright, I've looked into it:
- I don't think xs:complexType/xs:complexContent/xs:sequence is valid XSD. complexContent allows extensions or restrictions only. xs:complexType/xs:complexContent/xs:extension/xs:sequence does work.
- The other problem is probably caused by an error in the latest version. The commented-out code at '<!-- add inherited extensions; superfluous: taken care of by apply-templates statement above' should be included after all. If you include that code, it probably works. Note that this can introduce some elements being rendered duplicate; I'll add a proper fix for that.

**Comment by Light14** [comment] 2017-11-15 13:27
Thank you for reply.
You right - xs:complexContent/xs:sequence is invalid. Sorry for this.
After uncommenting code works, thank you. At this time i didn't found any duplicates.

**Comment by Light14** [comment] 2017-11-17 17:02
<xs:complexType name="complex1">
  <xs:complexContent>
    <xs:extension **base**="**extb:SomeBase**">
    </xs:extension>
  </xs:complexContent>
</xs:complexType>

...
In another, included file:
<xs:complexType name="**SomeBase**">
  <xs:sequence>
    <xs:element name="ExtBaseElement" type="sometype">
    </xs:element>
  </xs:sequence>
</xs:complexType>

Sorry for my new ask. Should this `extension base=...` work? 
Thank you

**Comment by MichielCM** [comment] 2017-11-28 20:14
Hopefully I just fixed the bugs with xs:extension elements and the element duplicating. Can you check with the newest commit?

https://github.com/MichielCM/xsd2html2xml/blob/master/xsd%2Bxml2html.xsl

**Comment by Light14** [comment] 2017-11-30 13:50
As I can see, <xs:extension base="..."> not fully working in this version.
I check using this xsd:

```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:inc_ns="inc_namespace"
targetNamespace="this_ns" elementFormDefault="qualified">
  <xs:import namespace="inc_namespace" schemaLocation="inc_namespace.xsd"/>  

  <xs:element name="test" >
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="inc_ns:BaseType">
          <xs:sequence>
            <xs:element name="DepatureCustoms" type="xs:string">
            </xs:element>
          </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

Included file:

```
	<xs:import namespace="inc2_ns" schemaLocation="inc2.xsd"/>
<xs:complexType name="BaseType">
   <xs:sequence>
      <xs:element name="el1" type="inc2_ns:IncludedType">
      </xs:element>
   </xs:sequence>
</xs:complexType>
```

In this example inc2_ns:IncludedType isn't loading.

I'm also trying to modify your template, results was: xs:extension[@base] recursively loading, but had problems with duplicated elements and xs:choice's, included within @base's of xs:extension.

**Comment by MichielCM** [comment] 2017-12-01 15:06
That's shame to hear. Can you upload the full files so I can take a look?

Alternatively, here's an example I worked with that shows how extensions work with different imported namespaces:

[extensions-sample.zip](https://github.com/MichielCM/xsd2html2xml/files/1521975/extensions-sample.zip)

**Comment by Light14** [comment] 2017-12-02 20:31
I use this set of files:
[extensions-test.zip](https://github.com/MichielCM/xsd2html2xml/files/1524125/extensions-test.zip)
In this set, one type with extension[@base] uses other type which is also have extension[@base], but @base not including.
Thank you

**Comment by MichielCM** [comment] 2017-12-29 15:43
Hi there,

It took me a while to fix it, may I managed. The newest commit displays your sample XSDs correctly and generates valid XML from it.

Please let me know if it worked for you.

Best regards,
Michiel

**Closed** 2018-12-07 17:44 UTC
